services:
  transpiler:
    image: transpiler
    container_name: transpiler_container
    stdin_open: true
    tty: true
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    security_opt:
      - seccomp:unconfined      
    group_add:
      - "video"
    cap_add:
      - SYS_PTRACE
    working_dir: /workspace
    volumes:
      - ./:/workspace 
      - /data/gustavostahl/Datasets:/home/ubuntu/Datasets
      - /home/ahmed/cuda-amd-bench:/home/ubuntu/cuda-amd-bench
      - /home/ahmed/.cache/huggingface/datasets:/root/.cache/huggingface/datasets
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    entrypoint: ["/usr/bin/bash"]